name: Micra_Fourteen
version: '${version}'
main: plugin.micra_fourteen.Main
api-version: '1.20'
commands:
  setMagic:
    description: "「/setmagic　魔法コマンド名(引数)」のコマンドを使って、以下の魔法が使用可能です"」

                "・魔法コマンド名一覧"

                  "fireball　→炎攻撃"

                  "summon golem　→ゴーレム召喚(※プレーヤーが、ゴーレムにダメージを与えると攻撃してくるので、要注意!!)"

                  "summon niwatori　→ニワトリ召喚"

                  "cure　→体力回復"

                  "recovery　→状態異常回復(例)毒をなおす"

                  "speed　→時間制限ありのプレーヤーのスピードアップ"
 
                  "defense　→時間制限ありのプレーヤーの防御力アップ"

                 "fly　→プレーヤーが空を飛ぶ ※スペースキー→上昇しながら飛ぶ　Shiftキー→降りる"

                "invisibility　→時間制限ありの透明化"

                "shield　→盾を入手"

                  "sword　→剣を入手"

                   "time　→現在時刻を表示"
 
                  "currentlocation　→現在位置"

                  "lightning　→雷攻撃　※自滅魔法"

                 "damage　→プレーヤー自身が数秒で自滅 ※自滅魔法"

                "poison →プレーヤー自身が、毒状態になる。※自滅魔法"

